services:
  web:
    build: .
    container_name: website
    ports:
      - "6767:5000"
    volumes:
      - .:/site
    restart: unless-stopped
    env_file:
      - .env

  backup:
    image: offen/docker-volume-backup:v2
    container_name: website_backup
    volumes:
      - .:/backup/the_slab:ro
      - /mnt/mediadrive/backups:/archive
    environment:
      - BACKUP_CRON_EXPRESSION=0 2 * * *
      - BACKUP_RETENTION_DAYS=14
      - BACKUP_FILENAME=the-slab-backup-%Y-%m-%dT%H-%M-%S.tar.gz
    restart: unless-stopped
