"""add unlocked_backgrounds column

Revision ID: b7d24f502123
Revises: a3cb0cc36d6d
Create Date: 2026-04-25 16:58:52.224283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d24f502123'
down_revision = 'a3cb0cc36d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked_backgrounds', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('unlocked_backgrounds')

    # ### end Alembic commands ###
